In [1]:
import numpy as np
x = np.array(range(12))
y = np.array(range(12,0,-1))
print x, y

[ 0  1  2  3  4  5  6  7  8  9 10 11] [12 11 10  9  8  7  6  5  4  3  2  1]


In [2]:
x = x.reshape((3,4))
y = y.reshape((3,4))
print x, '\n' ,y

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 
[[12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]]


In [3]:
x_mean = np.mean(x, axis=0)
y_mean = np.mean(y, axis=0)
print x_mean, '\n', y_mean

[ 4.  5.  6.  7.] 
[ 8.  7.  6.  5.]


In [4]:
data_cov = np.cov(x, rowvar=0)
print data_cov

[[ 16.  16.  16.  16.]
 [ 16.  16.  16.  16.]
 [ 16.  16.  16.  16.]
 [ 16.  16.  16.  16.]]


In [5]:
x = np.array(np.random.rand(10, 5))
y = np.array(np.random.rand(10, 5))
x_mean = np.mean(x, axis=0)
y_mean = np.mean(y, axis=0)
print x_mean, '\n', y_mean

[ 0.51637995  0.38254771  0.66754925  0.57919817  0.67964138] 
[ 0.7509466   0.51877747  0.63256328  0.4915336   0.53362491]


In [6]:
x_cov = np.cov(x, rowvar=False)
print x_cov

[[ 0.11305208 -0.00866714  0.0173452   0.03274659  0.00593715]
 [-0.00866714  0.04875193 -0.01959524 -0.00878316 -0.01464359]
 [ 0.0173452  -0.01959524  0.1045815  -0.00371081 -0.03188849]
 [ 0.03274659 -0.00878316 -0.00371081  0.074177    0.019774  ]
 [ 0.00593715 -0.01464359 -0.03188849  0.019774    0.03560701]]


In [7]:
y_cov = np.cov(y, rowvar=False)
print y_cov

[[ 0.04359554  0.02834288 -0.00923583  0.00525878  0.01842707]
 [ 0.02834288  0.06450501  0.01556818  0.03144872 -0.01631022]
 [-0.00923583  0.01556818  0.04789501  0.02859207 -0.03123996]
 [ 0.00525878  0.03144872  0.02859207  0.06375042 -0.03105138]
 [ 0.01842707 -0.01631022 -0.03123996 -0.03105138  0.1180773 ]]


In [27]:
from scipy.stats import multivariate_normal
rv = multivariate_normal(x_mean, x_cov)
p = np.array([0.48788206,  0.39793033,  0.5058051,   0.62318351,  0.55130692])
print rv.pdf([np.inf, np.inf, np.inf, np.inf, np.inf])

nan


In [31]:
import scipy.integrate as integrate

result = integrate.nquad(rv.pdf, [[-np.inf, np.inf]])
print result

TypeError: 'float' object is not iterable

[[-inf, inf], [-inf, inf], [-inf, inf], [-inf, inf], [-inf, inf]]