In [1]:
import numpy as np
x = np.array(range(12))
y = np.array(range(12,0,-1))
print x, y

[ 0  1  2  3  4  5  6  7  8  9 10 11] [12 11 10  9  8  7  6  5  4  3  2  1]


In [2]:
x = x.reshape((3,4))
y = y.reshape((3,4))
print x, '\n' ,y

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 
[[12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]]


In [3]:
x_mean = np.mean(x, axis=0)
y_mean = np.mean(y, axis=0)
print x_mean, '\n', y_mean

[ 4.  5.  6.  7.] 
[ 8.  7.  6.  5.]


In [4]:
data_cov = np.cov(x, rowvar=0)
print data_cov

[[ 16.  16.  16.  16.]
 [ 16.  16.  16.  16.]
 [ 16.  16.  16.  16.]
 [ 16.  16.  16.  16.]]


In [5]:
x = np.array(np.random.rand(10, 5))
y = np.array(np.random.rand(10, 5))
x_mean = np.mean(x, axis=0)
y_mean = np.mean(y, axis=0)
print x_mean, '\n', y_mean

[ 0.34895476  0.28262495  0.36597387  0.50654126  0.55747283] 
[ 0.56417711  0.41493629  0.57171321  0.31268382  0.46352508]


In [6]:
x_cov = np.cov(x, rowvar=False)
print x_cov

[[ 0.10704537 -0.04443033 -0.00919889 -0.00818643 -0.03047084]
 [-0.04443033  0.03624635  0.0078423   0.01357903  0.02986834]
 [-0.00919889  0.0078423   0.05306966 -0.02906532  0.04037349]
 [-0.00818643  0.01357903 -0.02906532  0.06467092 -0.00510046]
 [-0.03047084  0.02986834  0.04037349 -0.00510046  0.07007395]]


In [7]:
y_cov = np.cov(y, rowvar=False)
print y_cov

[[ 0.09606363  0.0551682  -0.0038834  -0.00091861 -0.03146434]
 [ 0.0551682   0.09679363 -0.04377968  0.00383059 -0.04284669]
 [-0.0038834  -0.04377968  0.07197347  0.020604   -0.00838057]
 [-0.00091861  0.00383059  0.020604    0.0818756   0.00197919]
 [-0.03146434 -0.04284669 -0.00838057  0.00197919  0.12114617]]


In [8]:
from scipy.stats import multivariate_normal
rv = multivariate_normal(x_mean, x_cov)
p = np.array([0.48788206,  0.39793033,  0.5058051,   0.62318351,  0.55130692])
print rv.pdf(p)

3.66737596693


In [10]:
np.linalg.det(rv.cov)

8.2402988929403179e-08